### ISSUE TITLE
Error when starting on Darwin Arm64 and Windows IA32

### ISSUE THREAD

**Issue by H29A** [witcher112/electron-app-universal-protocol-client#1]
Hey, you did an amazing job, thank you very much. Could you tell me how I can get your library to work on Darwin arm64 and Windows ia32? I would be very grateful. I understand that I need to build native modules for these architectures, but I don’t really understand how to do this, I’m new to this. Now when running on Darwin arm64 I get the error:

Uncaught Exception:
Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=110 uv=1 armv=8 libc=glibc node=16.17.1 electron=22.3.21
loaded from: /Applications/application_name.app/Contents/Resources/node_modules/electron-app-universal-protocol-client

at load.resolve.load.path (/Applications/application_name.app/Contents/Resources/node_modules/node-gyp-build/node-gyp-build.js:60:9)
at load (/Applications/application_name.app/Contents/Resources/node_modules/node-gyp-build/node-gyp-build.js:22:30)
at Object.<anonymous> (/Applications/application_name.app/Contents/Resources/node_modules/electron-app-universal-protocol-client/dist/bindings.js:3:53)
at Module._compile (node:internal/modules/cjs/loader:1141:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13330)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)

**Comment by witcher112** [comment]
Hi,

while ia32 seems doable right now, M1 is problematic as GitHub actions support for M1 workers is still pending as of this moment (https://github.com/github/roadmap/issues/528). Nevertheless, as the source code of this package is not being changed a lot right now, I'll provide M1 builds by myself.

**Comment by H29A** [comment]
> Hi,
> 
> 
> 
> while ia32 seems doable right now, M1 is problematic as GitHub actions support for M1 workers is still pending as of this moment (https://github.com/github/roadmap/issues/528). Nevertheless, as the source code of this package is not being changed a lot right now, I'll provide M1 builds by myself.

Thanks for the answer, in the end I did just that, I assemble Arm64 on my machine, I’ve already figured out ia32.

**Comment by dnlbln** [comment]
@H29A @witcher112 Can any of you two point in the direction of what I have to do to get it running on my mac. I am having the same issue but do not have much experience with this topic. Any help would be appreciated.

**Comment by witcher112** [comment]
@dnlbln I'll post an update next week that should fix the situation for Mac M1.

**Comment by lauri865** [comment]
Any update on this @witcher112? Would love a better DX working with deeplinks in dev on an M2 Mac 🙏

**Comment by witcher112** [comment]
Sorry it took so long (I was overwhelmed by work, no time for GitHub contributions), and thank you for reminding me about this one! :)

https://github.com/witcher112/electron-app-universal-protocol-client/releases/tag/v1.2.0 - I've just released a new version with darwin-arm64 (M1/M2) support.

I hope it will serve you all well :D

PS. I've also added a section about macOS permissions issue as it occurred to me while creating this update - https://github.com/witcher112/electron-app-universal-protocol-client#macos-development-mode-permissions-issue

**Comment by lauri865** [comment]
Thanks a lot @witcher112! How do I actually get it to load the prebuilds? Still getting the following error:

```
Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=119 uv=1 armv=8 libc=glibc node=18.18.2 electron=28.0.0-beta.11
    loaded from: /Users/xxx/dev/yyy/apps/desktop/.vite

    at y.resolve.y.path (/Users/xxx/dev/yyy/apps/desktop/.vite/build/main.js:1:2034)
    at y (/Users/xxx/dev/yyy/apps/desktop/.vite/build/main.js:1:1376)
    at /Users/xxx/dev/yyy/apps/desktop/.vite/build/main.js:3:2099
    at Object.<anonymous> (/Users/xxx/dev/yyy/apps/desktop/.vite/build/main.js:3:2127)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
```

Running electron with electron-forge vite plugin.

**Comment by witcher112** [comment]
@lauri865 could you create another issue with some additional information about your setup for electron-forge vite (ideally something I can easily reproduce)? Then I'd be able to check it out.

(I want to keep this issue closed as it resolved the problem of not having darwin-arm64 prebuilds)
